### ISSUE TITLE
"Uncaught SyntaxError: Unexpected token < " when there are no errors logged

### ISSUE THREAD

**Issue by kumarvikram** [Lapple/ErrorBoard#13]
![capture](https://cloud.githubusercontent.com/assets/5526914/5218538/2f80d522-7674-11e4-919e-17e91c6b65cc.PNG)

Also, I don't see any data on dashboard. 

![capture1](https://cloud.githubusercontent.com/assets/5526914/5218563/614246ea-7674-11e4-9007-b3f7bced33b9.PNG)

**Comment by Lapple** [comment]
Could not reproduce with a fresh install. Is this still a problem for you?

**Comment by kumarvikram** [comment]
Yes it is still reproducible. 
http://stackoverflow.com/questions/25005278/undefined1-doctype-html-syntaxerror-unexpected-token-node-js might be helpful for you.

What's wrong with graph or it is as designed?

**Comment by kumarvikram** [comment]
The error only comes when you have no messages logged.

**Comment by Lapple** [comment]
Ah, found it. It happens when you start the server without first building static `app.js`, so express falls back to serving index page.

Try starting the app with `npm start` instead of `node eb.js`. Alternatively you can first build `app.js` manually by calling `npm run browserify`.

**Comment by kumarvikram** [comment]
Thanks Aziz.
I am using forever(https://github.com/foreverjs/forever) to keep it running even if I close the console so,
I just do <code>forever start eb.js</code>

**Comment by Lapple** [comment]
I think running it with

    npm run browserify && forever start eb.js

will resolve the issue.

**Comment by kumarvikram** [comment]
Thanks Aziz. It worked.

**Comment by hokien1992** [comment]
sdfsdfsd

**Comment by hokien1992** [comment]
sdfsdf

**Comment by hokien1992** [comment]
ádasd
