### ISSUE TITLE
How about the performance?

### ISSUE THREAD

**Issue by amio** [Lapple/ErrorBoard#14]
The NeDB says:

> Its goal is to provide you with a clean and easy way to query data and persist it to disk, for web applications that do not need lots of concurrent connections, for example a continuous integration and deployment server and desktop applications built with Node Webkit.

Will it suitable for an event tracker backend?

**Comment by Lapple** [comment]
ErrorBoard was initially written for small teams or startups, so I valued ease of bootstrapping over peperformance.

However, database interaction can be made more extensible by using database adapter, for example, Waterline ORM.

**Comment by amio** [comment]
Got it, I'm planning to test it on a site which have nearly 40k/min PV, hope everything goes well!
