### ISSUE TITLE
Why include `node_modules` into repo?

### ISSUE THREAD

**Issue by amio** [Lapple/ErrorBoard#17]
Was it for some reason to be like that?

**Comment by amio** [comment]
I have tried split the `node_modules` out, here is the result https://github.com/amio/eb , the repo size has been significantly reduced.

before:
```bash
» git count-objects -vH
count: 0
size: 0 bytes
in-pack: 10513
packs: 1
size-pack: 12.20 MiB
prune-packable: 0
garbage: 0
size-garbage: 0 bytes
```

after:
```bash
» git count-objects -vH
count: 0
size: 0 bytes
in-pack: 701
packs: 1
size-pack: 483.80 KiB
prune-packable: 0
garbage: 0
size-garbage: 0 bytes
```

**Comment by Lapple** [comment]
When I released the original version node deps were excluded from the repo. However, it turned out that some deps were not following semver, so I updated and checked them into the repository to prevent future breakages.

As for the size, one would still need to download those deps before running the app.

Do you think it is inconvenient or there are more reasons to exclude node_modules?

**Comment by amio** [comment]
I thought if anyone update the dependencies for some reason, they will have a modified repo, then update the code base will be complicate.

If some deps were not following semver, how about declare it as a fixed version '1.2.3' instead of '~1.2.3', or use https://docs.npmjs.com/cli/shrinkwrap to lock deeply versions?

**Comment by amio** [comment]
@Lapple What do you think about it?

**Comment by Lapple** [comment]
Sorry, for now I am not convinced that there is a reason change current situation.

Let's also consider people who would pull this repo occasionally - if we remove deps, they will update to an app that doesn't work.

**Comment by amio** [comment]
Surely I understand.
I appreciate your current work, would you mind I continue working on a separated repo? I prefer to have a thinner repo, and in anytime I would be glad to merge things back to ErrorBoard :)

**Comment by Lapple** [comment]
I definitely support it, ErrorBoard is a self hosted app, and those who use it for their daily work surely know how to make it better.

**Comment by amio** [comment]
Great thanks :D

**Comment by kumarvikram** [comment]
Lets keep the node_modules with repo. After all a user has to download the packages either from this repo or via npm.
