### ISSUE TITLE
Unable to start ErrorBoard using npm start

### ISSUE THREAD

**Issue by kumarvikram** [Lapple/ErrorBoard#23]
Below is the log output:
0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'start' ]
2 info using npm@1.4.9
3 info using node@v0.10.28
4 verbose node symlink C:\Program Files\nodejs\\node.exe
5 verbose run-script [ 'prestart', 'start', 'poststart' ]
6 info prestart ErrorBoard@2.0.0
7 info start ErrorBoard@2.0.0
8 verbose unsafe-perm in lifecycle true
9 info ErrorBoard@2.0.0 Failed to exec start script
10 error ErrorBoard@2.0.0 start: `npm run browserify && npm run uglify && node eb.js`
10 error Exit status 1
11 error Failed at the ErrorBoard@2.0.0 start script.
11 error This is most likely a problem with the ErrorBoard package,
11 error not with npm itself.
11 error Tell the author that this fails on your system:
11 error     npm run browserify && npm run uglify && node eb.js
11 error You can get their info via:
11 error     npm owner ls ErrorBoard
11 error There is likely additional logging output above.
12 error System Windows_NT 6.2.9200
13 error command "C:\\Program Files\\nodejs\\\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "start"
14 error cwd D:\Apps\ErrorBoard
15 error node -v v0.10.28
16 error npm -v 1.4.9
17 error code ELIFECYCLE
18 verbose exit [ 1, true ]

node eb.js works but npm start doesn't

**Comment by Lapple** [comment]
Excuse me for such a long delay, the problem is that `browserify` script sets `NODE_ENV`, which is wrong syntax in `cmd.exe`, as far as I understood. I will remove the setting, don't think it's crucial for the application, thanks!
