### ISSUE TITLE
Why forceUpdate report page every hour

### ISSUE THREAD

**Issue by codinfox** [Lapple/ErrorBoard#24]
This line: https://github.com/Lapple/ErrorBoard/blob/master/client/component-report.jsx#L85

The report page is forced ti update every hour. According to [react documentation](https://facebook.github.io/react/docs/component-api.html#forceupdate): 

> If your render() method reads from something other than this.props or this.state, you'll need to tell React when it needs to re-run render() by calling forceUpdate(). You'll also need to call forceUpdate() if you mutate this.state directly.

But I didn't see any outside data rendered in this application. Why force update at all?

**Comment by Lapple** [comment]
If I remember correctly, this was done to redraw the earliest-latest report line. Having revisited the code, I believe it is possible to use the last refreshed timestamp for that, thanks for spotting!
